<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masukan Alamat</name>
   <tag></tag>
   <elementGuidId>747facbf-7ca2-40db-97a6-18bc626f2a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.addAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aedeb336-9230-4e3a-87f3-d5bf2237e075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addAddress</value>
      <webElementGuid>6a509a38-b08e-491d-800e-de991e223fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukan Alamat</value>
      <webElementGuid>06f2a668-618b-4638-8bf7-beb98cd058f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;SupplyChain&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;SCMModal&quot;]/div[@class=&quot;containerModal false&quot;]/div[@class=&quot;ModalBody&quot;]/div[@class=&quot;OfferingAddress&quot;]/div[@class=&quot;addAddress&quot;]</value>
      <webElementGuid>aa3c830c-d2a1-4d8d-a9d4-72d98c5993bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>d623a4fc-b802-4256-a9d0-5eda6f5e3c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukan alamat pengiriman agar supplier yang ditampilkan sesuai dengan lokasimu.'])[1]/following::div[1]</value>
      <webElementGuid>e2b9b2f3-7178-41f9-888a-adedd9498839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukan/pilih alamat untuk melanjutkan'])[1]/following::div[1]</value>
      <webElementGuid>878c4991-29af-408c-94a9-70e4d014754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>31995cd3-5bd6-4763-a853-c1d7d5bd20b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Masukan Alamat' or . = 'Masukan Alamat')]</value>
      <webElementGuid>07646886-a57e-4427-a7c0-31d2edf23f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
