<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Belanja Stok</name>
   <tag></tag>
   <elementGuidId>09832072-88e6-4c57-ae36-f3e6ea8b4f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[2]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48072616-98db-4071-90b0-2df3830ec10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-menu</value>
      <webElementGuid>b2134c28-0e87-4abc-8a67-600bcc82b136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/belanja-stok</value>
      <webElementGuid>6e13461c-0570-4220-a480-b779b7a323a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belanja Stok</value>
      <webElementGuid>4d7c828a-3428-473b-999c-27337d4c4ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;overview-main-container&quot;]/div[1]/div[@class=&quot;side-menubar&quot;]/div[@class=&quot;site-menubar-body&quot;]/ul[@class=&quot;site-menu&quot;]/li[@class=&quot;side-menu-item has-sub&quot;]/a[@class=&quot;list-menu&quot;]</value>
      <webElementGuid>d291871b-710d-461f-8cc2-754f3d3ec05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>644351c9-fb08-4585-bfd2-afe7146e8884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-menu</value>
      <webElementGuid>cd281074-66e4-4f2c-9180-258f2f558afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/belanja-stok</value>
      <webElementGuid>57feeeb3-2e66-401b-a4dc-98ddf39fe6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belanja Stok</value>
      <webElementGuid>07279f34-54a7-4ed0-a711-b881fe08a538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;overview-main-container&quot;]/div[1]/div[@class=&quot;side-menubar&quot;]/div[@class=&quot;site-menubar-body&quot;]/ul[@class=&quot;site-menu&quot;]/li[@class=&quot;side-menu-item has-sub&quot;]/a[@class=&quot;list-menu&quot;]</value>
      <webElementGuid>67220ae9-2e22-4b21-b115-2c7d024060e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>b51e5c41-577c-4d0f-a58e-87ce31bb0fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Analisis Produk'])[1]/following::a[1]</value>
      <webElementGuid>fcbcbe89-a68b-4c62-a9af-0431de6137db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi'])[1]/following::a[2]</value>
      <webElementGuid>8ea01c5a-ad52-497d-96e0-62377731dcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Akun'])[1]/preceding::a[1]</value>
      <webElementGuid>a5b056d5-6e8e-4f57-a3ab-743953155506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/belanja-stok')]</value>
      <webElementGuid>62e38839-5c42-4149-903c-2a9f31a50b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>cdcc7410-bcc8-4646-8dec-1287b4f7f2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/belanja-stok' and (text() = 'Belanja Stok' or . = 'Belanja Stok')]</value>
      <webElementGuid>d5c9d6f3-738e-4fea-b03b-f1d67908fda5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
