<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Keranjang</name>
   <tag></tag>
   <elementGuidId>ae0a5235-f065-4097-b289-0a99a9399e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outside']/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cartLinkButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32c00036-c716-4a41-a9d1-e016c6da1577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/belanja-stok/cart</value>
      <webElementGuid>ad29713c-c790-4413-bf37-083847c6feed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartLinkButton</value>
      <webElementGuid>753eebb8-2bba-43b0-b70d-114cca1c4454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Keranjang</value>
      <webElementGuid>44526d9f-1381-4945-8a4b-ea8cc9363424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outside2&quot;)/div[@id=&quot;outside&quot;]/div[@class=&quot;modalContainer&quot;]/div[@class=&quot;bodyBox&quot;]/div[@class=&quot;confirmationBodyContainer&quot;]/div[@class=&quot;leftContainer&quot;]/a[@class=&quot;cartLinkButton&quot;]</value>
      <webElementGuid>6323de10-35e5-4228-85b2-8ea5ba16a15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b93e00fa-8aa0-4fa7-bdba-c50f89b422b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/belanja-stok/cart</value>
      <webElementGuid>4f277bb5-0630-48d7-b98d-97e8b755d6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartLinkButton</value>
      <webElementGuid>e1cdba9f-9ed9-4357-ba72-927a18eb8c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Keranjang</value>
      <webElementGuid>a78e7dea-548f-4654-a9e2-daae176b2338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outside2&quot;)/div[@id=&quot;outside&quot;]/div[@class=&quot;modalContainer&quot;]/div[@class=&quot;bodyBox&quot;]/div[@class=&quot;confirmationBodyContainer&quot;]/div[@class=&quot;leftContainer&quot;]/a[@class=&quot;cartLinkButton&quot;]</value>
      <webElementGuid>6578960d-b2d0-40b8-9bf3-a1f040051480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outside']/div/div[2]/div/div/a</value>
      <webElementGuid>c525e5c3-9418-43fb-b39a-7a35ec87d53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Keranjang')]</value>
      <webElementGuid>9dfea1b8-23de-4075-a01f-5c1ba3d8e3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aqua'])[1]/following::a[1]</value>
      <webElementGuid>db260e51-f51f-46d2-baa4-daf56bb1590b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barang berhasil ditambahkan'])[1]/following::a[1]</value>
      <webElementGuid>82fc5239-147e-45ab-835e-5b8323cedd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim Ke:'])[1]/preceding::a[4]</value>
      <webElementGuid>c6970b45-b9d0-4df0-b91c-a0bbcc1dbeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Rumah'])[1]/preceding::a[4]</value>
      <webElementGuid>c6c74e81-c2d4-4ae7-b459-a7dde610d198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Keranjang']/parent::*</value>
      <webElementGuid>364dd8ce-01ff-4dfc-a4c0-c63df65f66b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/belanja-stok/cart')]</value>
      <webElementGuid>7b57dd7a-5646-47a6-8e4a-b4ab2d0c6724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>0e2833e4-8b7c-4a8d-b5ec-ec1ead942c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/belanja-stok/cart' and (text() = 'Lihat Keranjang' or . = 'Lihat Keranjang')]</value>
      <webElementGuid>b06210e3-da9d-43eb-b2fc-af5972ae3650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CRYSTALLINE 330ML'])[1]/following::a[1]</value>
      <webElementGuid>984a6dc3-c9d0-40dd-a7ad-6a8bfe731e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
