<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambah ke Keranjang</name>
   <tag></tag>
   <elementGuidId>9d709afc-607c-42ff-9ba3-b149dc11d449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outside2']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0746d702-2183-4e1d-aa8a-543e10b48d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>b0d4df93-7d07-4af4-9d87-baa94a35603a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah ke Keranjang</value>
      <webElementGuid>05673c30-d6ed-45ea-a960-fe93db666dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outside2&quot;)/div[@class=&quot;btn&quot;]</value>
      <webElementGuid>17d34a2f-891a-4b2d-a540-d11e8ffc6ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5eb722a8-5271-4446-a007-acd2d995cb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>faa09673-61b2-40f9-947f-179e5ae99f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah ke Keranjang</value>
      <webElementGuid>daa004d2-54a4-4035-aba4-8795de072185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outside2&quot;)/div[@class=&quot;btn&quot;]</value>
      <webElementGuid>10f21e91-3b49-4ff8-b9c4-e0f257cf7ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outside2']/div</value>
      <webElementGuid>014cb802-1636-4bb3-8b0f-64dc1be30c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOKO ARJUNA XIII'])[1]/following::div[3]</value>
      <webElementGuid>b06cd30f-8712-423a-8fe2-16b8e7686d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim Ke:'])[1]/preceding::div[6]</value>
      <webElementGuid>4f5b7e50-1a1f-47ba-86bb-5f06f47ed7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>1c6e3f33-678c-4f26-834a-5990c0daf621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tambah ke Keranjang' or . = 'Tambah ke Keranjang')]</value>
      <webElementGuid>0a5fdcac-eeec-41f4-88d6-3b4c07563fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBAT PANGAN'])[1]/following::div[3]</value>
      <webElementGuid>e91feffa-d38d-4f33-9da9-e8937af8e129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
