<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Rp51.000_changeValue rs-icon rs-icon-plus_328534</name>
   <tag></tag>
   <elementGuidId>5d4436a2-03f1-42fe-9e41-f8885a0ebcb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outside']/div/div[2]/div/div[2]/i[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.changeValue.rs-icon.rs-icon-plus.rs-icon-size-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8fada4fc-c07c-4d06-af01-622dab29a536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeValue rs-icon rs-icon-plus rs-icon-size-2x</value>
      <webElementGuid>09a86d32-5892-4185-b3de-8a918138bbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outside&quot;)/div[@class=&quot;detailModalContainer&quot;]/div[@class=&quot;modalContent&quot;]/div[@class=&quot;leftContent&quot;]/div[@class=&quot;quantityContainer&quot;]/i[@class=&quot;changeValue rs-icon rs-icon-plus rs-icon-size-2x&quot;]</value>
      <webElementGuid>231eb107-8fbd-413b-84cf-84dae3f4fbc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outside']/div/div[2]/div/div[2]/i[2]</value>
      <webElementGuid>0b28c570-41ad-4233-88c7-25bf42580abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>cb6719b7-4dac-4b30-b0aa-7be3119e7f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
