<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Virtual Account_btnClose rs-icon rs-icon-_a1401e</name>
   <tag></tag>
   <elementGuidId>8ad29b09-ac92-4c80-add7-b77063f22f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='backdrop']/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.btnClose.rs-icon.rs-icon-close.rs-icon-size-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>713d3df3-9799-4a60-bd5b-601e87d58a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnClose rs-icon rs-icon-close rs-icon-size-lg</value>
      <webElementGuid>d754b55c-a463-4eaf-b74e-64a20f1e0d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;backdrop&quot;)/div[@class=&quot;paymentListCard d-flex flex-column&quot;]/div[@class=&quot;header d-flex flex-row&quot;]/i[@class=&quot;btnClose rs-icon rs-icon-close rs-icon-size-lg&quot;]</value>
      <webElementGuid>4fe934cd-a979-4773-9ddc-9c89ba85ade7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='backdrop']/div/div/i</value>
      <webElementGuid>640b8ffe-e9cd-4b21-84e5-d3ae695b485d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/i</value>
      <webElementGuid>c9cb8d07-00b3-48f9-88b2-d47b956f4480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
