<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Menu Lain_SCMSearchHeader_inputSearch__2bpsH</name>
   <tag></tag>
   <elementGuidId>f63019a3-4bdc-49f5-a5c2-88e091787c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.SCMSearchHeader_inputSearch__2bpsH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>137e25fd-99fb-4c2a-bfac-9b095b50d5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be9a05f3-3f88-4e30-b183-acc40d603093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Produk</value>
      <webElementGuid>7daa573a-0e7f-4175-8c37-9070cf68cce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SCMSearchHeader_inputSearch__2bpsH</value>
      <webElementGuid>3487fb1c-2d7e-4031-acff-bd12e0612ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;SupplyChain&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;MuiBox-root jss16 SCMSearchHeader_headerContainer__2gTkO&quot;]/div[@class=&quot;MuiBox-root jss17 SCMSearchHeader_topContainer__fpccL&quot;]/div[@class=&quot;MuiBox-root jss19 SCMSearchHeader_inputContainer__1ltn8&quot;]/input[@class=&quot;SCMSearchHeader_inputSearch__2bpsH&quot;]</value>
      <webElementGuid>153bc6b7-7d6a-47bb-9c07-02c0bf8dfe8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>a7af95bf-a617-4032-9e14-be4016e6b28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>d783695c-fcf8-4b80-8d64-64043b26a7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>46262e1d-0dd3-4718-a0a2-8cd672bec590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari Produk']</value>
      <webElementGuid>e09b111e-94cb-456d-a034-74b374b68f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
