<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp 153.000 - Copy</name>
   <tag></tag>
   <elementGuidId>3a2db8b6-c706-4574-b31a-e7e2dec068d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.subtotal-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5e7847a-e819-4919-8c4b-b8c857bca9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subtotal-price</value>
      <webElementGuid>d9591405-7ee9-4b3f-8b04-85e952afa9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp 153.000</value>
      <webElementGuid>e2aac8f9-ab67-443d-b125-2ec26e681ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Cart&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;container d-flex flex-column&quot;]/div[@class=&quot;cart-container&quot;]/div[@class=&quot;CartSupplier&quot;]/div[@class=&quot;container-box d-flex flex-row&quot;]/div[@class=&quot;detail-cart&quot;]/div[@class=&quot;containerSubtotal&quot;]/div[@class=&quot;subtotal-box d-flex flex-row&quot;]/span[@class=&quot;subtotal-price&quot;]</value>
      <webElementGuid>013fd58d-eb15-4595-8419-5d419fa392b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
