<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_10 Produk TerlarisProduk terlaris kamu masih kosongTambahkan produk tokomu ke Aplikasi Dagang atau Tablet Youtap untuk menikmati fitur ini</name>
   <tag></tag>
   <elementGuidId>67ccbac2-a797-4610-be88-62a36151d458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='left']/div[3])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd3e6c7d-0690-432a-8786-7f5e242654a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>div-card</value>
      <webElementGuid>942f3537-f902-4786-aa00-542411b2309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10 Produk TerlarisProduk terlaris kamu masih kosongTambahkan produk tokomu ke Aplikasi Dagang atau Tablet Youtap untuk menikmati fitur ini</value>
      <webElementGuid>71f7c037-ba4c-41db-aa31-a3ac159b0df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;overview-main-container&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;page-content container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;left&quot;]/div[@class=&quot;div-card&quot;]</value>
      <webElementGuid>bb39010f-ecb3-47c6-adba-1025105b6a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='left']/div[3])[2]</value>
      <webElementGuid>723d6053-95c8-42d7-a91c-fca5ed65ad7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada transaksi terbaru.'])[1]/following::div[1]</value>
      <webElementGuid>7e41808b-4724-46bb-9e56-278a1d216aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‌'])[30]/following::div[4]</value>
      <webElementGuid>ab436bcf-cacd-49c3-b572-84ef61fbcf78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[11]</value>
      <webElementGuid>a0a89331-270c-49dc-b10c-d00efcef5d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[11]</value>
      <webElementGuid>9598d805-a59c-4281-abd8-53e60b5802e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]</value>
      <webElementGuid>2fbefaf6-dec0-4843-85e8-3d34b9c7edf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '10 Produk TerlarisProduk terlaris kamu masih kosongTambahkan produk tokomu ke Aplikasi Dagang atau Tablet Youtap untuk menikmati fitur ini' or . = '10 Produk TerlarisProduk terlaris kamu masih kosongTambahkan produk tokomu ke Aplikasi Dagang atau Tablet Youtap untuk menikmati fitur ini')]</value>
      <webElementGuid>acb0da29-6196-4c3a-bfb0-a2bee103dddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
