<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Menu Lain_SCMSearchHeader_inputSearch__2bpsH</name>
   <tag></tag>
   <elementGuidId>4e845211-62d8-4eff-9514-40473081ef32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.SCMSearchHeader_inputSearch__2bpsH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b197a40e-e8a1-4243-90ab-e3b7d09f6d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cec68fde-477e-4d33-832f-fef2795a32ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Kebutuhan Usahamu di sini</value>
      <webElementGuid>0d317948-3cb7-4ffc-aea6-00ad9bfacb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SCMSearchHeader_inputSearch__2bpsH</value>
      <webElementGuid>e3cae641-ba88-4031-a695-34362a1bb6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;overview-main-container&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;MuiBox-root jss1 SCMSearchHeader_headerContainer__2gTkO&quot;]/div[@class=&quot;MuiBox-root jss2 SCMSearchHeader_topContainer__fpccL&quot;]/div[@class=&quot;MuiBox-root jss4 SCMSearchHeader_inputContainer__1ltn8&quot;]/input[@class=&quot;SCMSearchHeader_inputSearch__2bpsH&quot;]</value>
      <webElementGuid>7ed5995f-c70e-4f75-a54a-fd885a843a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>36c73a26-1ae8-42bf-b53b-30373cc09b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>d349cc29-0816-431b-9404-69873a03862f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d6376623-deaf-41d7-8ccc-889bfe3619c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari Kebutuhan Usahamu di sini']</value>
      <webElementGuid>3796b420-b58c-4b20-9481-6819c8376d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
